import {
  hostInternal,
  hostExternal,
  live,
  originInternal,
  originExternal,
} from "../host";
import { apwManager, temporaryPassword } from "../utils";
export { Models, ID, Query } from "node-appwrite";

export {
  // Account functions
  addPrefs,
  createAccount,
  createAnonymousSession,
  createEmailPasswordSession,
  createJWT,
  createMagicURLSession,
  createOAuth2Token,
  createPhoneVerification,
  createRecovery,
  createSession,
  createVerification,
  deletePrefs,
  deleteSession,
  deleteSessions,
  getAppUser,
  getCustomUser,
  getSession,
  getUser,
  listSessions,
  updateEmail,
  updateName,
  updatePassword,
  updatePhone,
  updatePhoneVerification,
  updateRecovery,
  updateSession,
  updateStatus,
  updateVerification,
} from "../methods-ssr/account";

export {
  // Avatars functions
  getBrowserIcon,
  getCreditCardIcon,
  getFavicon,
  getFlag,
  getImage,
  getInitials,
  getQr,
} from "../methods-ssr/avatars";

export {
  // Databases functions
  createBooleanAttribute,
  createCollection,
  createCollectionWithSchema,
  createDatabase,
  createDatetimeAttribute,
  createDocument,
  createEmailAttribute,
  createEnumAttribute,
  createFloatAttribute,
  createIndex,
  createIntegerAttribute,
  createIpAttribute,
  createRelationshipAttribute,
  createStringAttribute,
  createUrlAttribute,
  deleteAttribute,
  deleteCollection,
  deleteDatabase,
  deleteDocument,
  deleteIndex,
  getAttribute,
  getCollection,
  getDatabase,
  getDocument,
  getIndex,
  listAttributes,
  listCollections,
  listDatabases,
  listDocuments,
  listIndexes,
  updateBooleanAttribute,
  updateCollection,
  updateDatabase,
  updateDatetimeAttribute,
  updateDocument,
  updateEmailAttribute,
  updateEnumAttribute,
  updateFloatAttribute,
  updateIntegerAttribute,
  updateIpAttribute,
  updateRelationshipAttribute,
  updateStringAttribute,
  updateUrlAttribute,
} from "../methods-ssr/databases";

export {
  // Storage functions
  createBucket,
  deleteBucket,
  getBucket,
  getFile,
  getFileDownload,
  getFilePreview,
  getFileView,
  deleteFile,
  listBuckets,
  listFiles,
  updateBucket,
  updateFile,
  uploadFile,
  //uploadFileFromPath,
} from "../methods-ssr/storage";

export {
  // Teams functions
  createTeam,
  createTeamMembership,
  deleteTeam,
  deleteTeamMembership,
  getTeam,
  getTeamMembership,
  getTeamPreferences,
  listTeamMemberships,
  listTeams,
  updateTeamMembership,
  updateTeamMembershipStatus,
  updateTeamName,
  updateTeamPreferences,
} from "../methods-ssr/teams";

export {
  // Users functions
  addLabelsForUserId,
  addPrefsForUserId,
  createSessionForUserId,
  createToken,
  deleteLabelsForUserId,
  deletePrefsForUserId,
  deleteSessionForUserId,
  deleteSessionsForUserId,
  deleteUserForUserId,
  getAppUserForUserId,
  getCustomUserForUserId,
  getUserForUserId,
  listCustomUsers,
  listIdentities,
  listIdentitiesForUserId,
  listSessionsForUserId,
  listUsers,
  updateEmailForUserId,
  updateEmailVerificationForUserId,
  updateNameForUserId,
  updatePasswordForUserId,
  updatePhoneForUserId,
  updatePhoneVerificationForUserId,
  updateStatusForUserId,
} from "../methods-ssr/users";

export {
  // ApwWrapper Config
  envCheck,
  apiKeySsr,
  appDomain,
  cookiePrefix,
  cookieName,
  databaseId,
  endpoint,
  i18nPath,
  liveEnvVarName,
  oauthSuccessPath,
  oauthFailurePath,
  projectId,
  port,
  schemasPath,
  signInPath,
  userCollectionId,
  verificationPath,
} from "../appwriteConfig";

export {
  apwManager,
  temporaryPassword,
  hostInternal,
  hostExternal,
  live,
  originInternal,
  originExternal,
};
